### ISSUE TITLE
Missing some images in old posts

### ISSUE THREAD

**Issue by syohex** [tcnksm/deeeet.com#10]
For examples, demo animation gifs in following posts are missing.
- http://deeeet.com/writing/2014/06/15/dmux/
- http://deeeet.com/writing/2014/07/29/ghr/

I enjoy reading your blog posts.
Thank you so mush for posting excellent information.

**Comment by tcnksm** [comment]
Ah, Thanks, I'll update it.

**Comment by tcnksm** [comment]
Sorry for late, update images

**Comment by syohex** [comment]
Thanks
